AllCops:
  Exclude:
    - 'gemfiles/**'
  TargetRubyVersion: 2.4

AmbiguousRegexpLiteral:
  Enabled: false

AssignmentInCondition:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

# Enforcing this results in a lot of unnecessary indentation.
ClassAndModuleChildren:
  Enabled: false

CollectionMethods:
  Enabled: false

Documentation:
  Exclude:
    - 'spec/**/*'
    - 'lib/haml_lint/spec/**/*.rb'

DotPosition:
  EnforcedStyle: leading

FormatString:
  Enabled: false

FileName:
  Exclude:
    - 'bin/haml-lint'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'

GuardClause:
  Enabled: false

IfUnlessModifier:
  Enabled: false

Lambda:
  Enabled: false

LineLength:
  Max: 100

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*'
    - 'lib/haml_lint/spec/**/*.rb'

Lint/NestedPercentLiteral:
  Exclude:
    - lib/haml_lint/linter/multiline_script.rb

MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/haml_lint/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'lib/haml_lint/spec/**/*.rb'

# Prefer curly braces except for %i/%w/%W, since those return arrays.
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%': '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '()'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

# Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
# a "has-a" relationship.
PredicateName:
  Enabled: false

SignalException:
  Enabled: false

# Forcing a particular name (e.g. |a, e|) for inject methods prevents you from
# choosing intention-revealing names.
SingleLineBlockParams:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Void:
  Enabled: false
